config/routes.rb
Rails.application.routes.draw do
  resources :form_contract_values
  resources :form_fields
  resources :fields
  resources :forms
  resources :contracts do
    patch :values_form, on: :member
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/contract.rb
class Contract < ApplicationRecord
    has_one :form_contract_value, dependent: :destroy
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  before_action :set_contract, only: %i[ show edit update destroy add_form_contract_values values_form]
  after_action :add_form_contract_values, only: :create

  # GET /contracts or /contracts.json
  def index
    @contracts = Contract.all
  end

  # GET /contracts/1 or /contracts/1.json
  def show
    @forms = []
    Form.all.each do |form|
      @forms << form.form_key
    end
  end

  # GET /contracts/new
  def new
    @contract = Contract.new
  end

  # GET /contracts/1/edit
  def edit
  end

  # POST /contracts or /contracts.json
  def create
    @contract = Contract.new(contract_params)

    respond_to do |format|
      if @contract.save
        format.html { redirect_to contract_url(@contract), notice: "Contract was successfully created." }
        format.json { render :show, status: :created, location: @contract }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contracts/1 or /contracts/1.json
  def update
    respond_to do |format|
      if @contract.update(contract_params)
        format.html { redirect_to contract_url(@contract), notice: "Contract was successfully updated." }
        format.json { render :show, status: :ok, location: @contract }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contracts/1 or /contracts/1.json
  def destroy
    @contract.destroy

    respond_to do |format|
      format.html { redirect_to contracts_url, notice: "Contract was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def add_form_contract_values
    form_contract_value = FormContractValue.new(contract_id: @contract.id)
    form_contract_value.save
  end

  def values_form
    form_contract_value = @contract.form_contract_value
    form_contract_value.update(values: params["form_contract_field"])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contract
      @contract = Contract.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contract_params
      params.require(:contract).permit(:status, :subject, :form_key_value)
    end
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/views/contracts/_contract.html.erb
<div class="container">
  <div id="<%= dom_id contract %>">

    <p>
      <strong>Name:</strong>
      <%= contract.name %>
    </p>

    <p>
      <strong>Status:</strong>
      <%= contract.status %>
    </p>

    <p>
      <strong>Subject:</strong>
      <%= contract.subject %>
    </p>

    <h5>Standard forms:</h5>

    <%= simple_form_for contract, method: :PATCH, remote: true do |g| %>
        <%= g.select :form_key_value, @forms %>
        <%= g.submit "ok" %>
    <% end %>

    <%= simple_form_for :form_contract_field, url: values_form_contract_path(contract), method: :PATCH, remote: true do |f| %>
        <% Form.find_by_form_key(contract.form_key_value).form_fields.each do |form_field| %>
          <% if form_field.field.field_type == "string" || form_field.field.field_type == "integer" %>
            <%=
              f.input form_field.field.name,
              as: form_field.field.field_type,
              label: JSON.parse(form_field.settings)["label"],
              placeholder: JSON.parse(form_field.settings)["placeholder"],
              input_html: { required: JSON.parse(form_field.settings)["required"] }
            %>
          <% else %>
            <%=
              f.input form_field.field.name,
              label: JSON.parse(form_field.settings)["label"],
              as: form_field.field.field_type,
              collection: JSON.parse(form_field.settings)["value"],
              wrapper: :vertical_collection_inline,
              input_html: { required: JSON.parse(form_field.settings)["required"], 
                            multiple: JSON.parse(form_field.settings)["multiple"] 
                          }
            %>
          <% end %>
        <% end %>
        <%= f.submit "Save", class: "btn btn-primary px-5 my-3" %>
    <% end %>


  </div>
</div>

app/views/contracts/_form.html.erb
<%= form_with(model: contract) do |form| %>
  <% if contract.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contract.errors.count, "error") %> prohibited this contract from being saved:</h2>

      <ul>
        <% contract.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.label :subject, style: "display: block" %>
    <%= form.text_field :subject %>
  </div>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/contracts/edit.html.erb
<h1>Editing contract</h1>

<%= render "form", contract: @contract %>

<br>

<div>
  <%= link_to "Show this contract", @contract %> |
  <%= link_to "Back to contracts", contracts_path %>
</div>

app/views/contracts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Contracts</h1>

<div id="contracts">
  <% @contracts.each do |contract| %>
    <div id="<%= dom_id contract %>">
  <p>
    <strong>Status:</strong>
    <%= contract.status %>
  </p>

  <p>
    <strong>Subject:</strong>
    <%= contract.subject %>
  </p>
  
</div>

    <p>
      <%= link_to "Show this contract", contract %>
    </p>
  <% end %>
</div>

<%= link_to "New contract", new_contract_path %>

app/views/contracts/new.html.erb
<h1>New contract</h1>

<%= render "form", contract: @contract %>

<br>

<div>
  <%= link_to "Back to contracts", contracts_path %>
</div>

app/views/contracts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @contract %>

<div>
  <%= link_to "Edit this contract", edit_contract_path(@contract) %> |
  <%= link_to "Back to contracts", contracts_path %>

  <%= button_to "Destroy this contract", @contract, method: :delete %>
</div>