config/routes.rb
Rails.application.routes.draw do
  resources :form_contract_values
  resources :form_fields
  resources :fields
  resources :forms
  resources :contracts do
    patch :values_form, on: :member
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/form_contract_value.rb
class FormContractValue < ApplicationRecord
  belongs_to :contract
end

app/controllers/form_contract_values_controller.rb
class FormContractValuesController < ApplicationController
  before_action :set_form_contract_value, only: %i[ show edit update destroy ]

  # GET /form_contract_values or /form_contract_values.json
  def index
    @form_contract_values = FormContractValue.all
  end

  # GET /form_contract_values/1 or /form_contract_values/1.json
  def show
  end

  # GET /form_contract_values/new
  def new
    @form_contract_value = FormContractValue.new
  end

  # GET /form_contract_values/1/edit
  def edit
  end

  # POST /form_contract_values or /form_contract_values.json
  def create
    @form_contract_value = FormContractValue.new(form_contract_value_params)

    respond_to do |format|
      if @form_contract_value.save
        format.html { redirect_to form_contract_value_url(@form_contract_value), notice: "Form contract value was successfully created." }
        format.json { render :show, status: :created, location: @form_contract_value }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @form_contract_value.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /form_contract_values/1 or /form_contract_values/1.json
  def update
    respond_to do |format|
      if @form_contract_value.update(form_contract_value_params)
        format.html { redirect_to form_contract_value_url(@form_contract_value), notice: "Form contract value was successfully updated." }
        format.json { render :show, status: :ok, location: @form_contract_value }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @form_contract_value.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /form_contract_values/1 or /form_contract_values/1.json
  def destroy
    @form_contract_value.destroy

    respond_to do |format|
      format.html { redirect_to form_contract_values_url, notice: "Form contract value was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form_contract_value
      @form_contract_value = FormContractValue.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def form_contract_value_params
      params.require(:form_contract_value).permit(:values, :contract_id)
    end
end

app/helpers/form_contract_values_helper.rb
module FormContractValuesHelper
end

app/views/form_contract_values/_form.html.erb
<%= form_with(model: form_contract_value) do |form| %>
  <% if form_contract_value.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(form_contract_value.errors.count, "error") %> prohibited this form_contract_value from being saved:</h2>

      <ul>
        <% form_contract_value.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :values, style: "display: block" %>
    <%= form.text_field :values %>
  </div>

  <div>
    <%= form.label :contract_id, style: "display: block" %>
    <%= form.text_field :contract_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/form_contract_values/_form_contract_value.html.erb
<div id="<%= dom_id form_contract_value %>">
  <p>
    <strong>Values:</strong>
    <%= form_contract_value.values %>
  </p>

  <p>
    <strong>Contract:</strong>
    <%= form_contract_value.contract_id %>
  </p>

</div>

app/views/form_contract_values/edit.html.erb
<h1>Editing form contract value</h1>

<%= render "form", form_contract_value: @form_contract_value %>

<br>

<div>
  <%= link_to "Show this form contract value", @form_contract_value %> |
  <%= link_to "Back to form contract values", form_contract_values_path %>
</div>

app/views/form_contract_values/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Form contract values</h1>

<div id="form_contract_values">
  <% @form_contract_values.each do |form_contract_value| %>
    <%= render form_contract_value %>
    <p>
      <%= link_to "Show this form contract value", form_contract_value %>
    </p>
  <% end %>
</div>

<%= link_to "New form contract value", new_form_contract_value_path %>

app/views/form_contract_values/new.html.erb
<h1>New form contract value</h1>

<%= render "form", form_contract_value: @form_contract_value %>

<br>

<div>
  <%= link_to "Back to form contract values", form_contract_values_path %>
</div>

app/views/form_contract_values/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @form_contract_value %>

<div>
  <%= link_to "Edit this form contract value", edit_form_contract_value_path(@form_contract_value) %> |
  <%= link_to "Back to form contract values", form_contract_values_path %>

  <%= button_to "Destroy this form contract value", @form_contract_value, method: :delete %>
</div>