config/routes.rb
Rails.application.routes.draw do
  resources :form_contract_values
  resources :form_fields
  resources :fields
  resources :forms
  resources :contracts do
    patch :values_form, on: :member
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :set_form, only: %i[ show edit update destroy ]
  

  # GET /forms or /forms.json
  def index
    @forms = Form.all
  end

  # GET /forms/1 or /forms/1.json
  def show
    @form_field = FormField.new
  end

  # GET /forms/new
  def new
    @form = Form.new
  end

  # GET /forms/1/edit
  def edit
  end

  # POST /forms or /forms.json
  def create
    @form = Form.new(form_params)

    respond_to do |format|
      if @form.save
        format.html { redirect_to form_url(@form), notice: "Form was successfully created." }
        format.json { render :show, status: :created, location: @form }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  

  # PATCH/PUT /forms/1 or /forms/1.json
  def update
    respond_to do |format|
      if @form.update(form_params)
        format.html { redirect_to form_url(@form), notice: "Form was successfully updated." }
        format.json { render :show, status: :ok, location: @form }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forms/1 or /forms/1.json
  def destroy
    @form.destroy

    respond_to do |format|
      format.html { redirect_to forms_url, notice: "Form was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form
      @form = Form.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def form_params
      params.require(:form).permit(:name, :form_key, :settings)
    end
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/views/forms/_form.html.erb
<div id="<%= dom_id form %>">
  <p>
    <strong>Name:</strong>
    <%= form.name %>
  </p>

  <p>
    <strong>Settings:</strong>
    <%= form.settings %>
  </p>

</div>

app/views/forms/edit.html.erb
<h1>Editing form</h1>

<%= render "form", form: @form %>

<br>

<div>
  <%= link_to "Show this form", @form %> |
  <%= link_to "Back to forms", forms_path %>
</div>

app/views/forms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Forms</h1>

<div id="forms">
  <% @forms.each do |form| %>
    <%= render form %>
    <p>
      <%= link_to "Show this form", form %>
    </p>
  <% end %>
</div>

<%= link_to "New form", new_form_path %>

app/views/forms/new.html.erb
<h1>New form</h1>
<%= form_with(model: @form) do |form| %>


  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :form_key, style: "display: block" %>
    <%= form.text_field :form_key %>
  </div>

  <div>
    <%= form.label :settings, style: "display: block" %>
    <%= form.text_field :settings %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<br>

<div>
  <%= link_to "Back to forms", forms_path %>
</div>

app/views/forms/show.html.erb
<div class="container">

  <p style="color: green"><%= notice %></p>

  <%= render @form %>

  <% @form.form_fields.each do |form_field| %>
    <%= simple_form_for :form_field, url: form_field_path(form_field), method: :patch, remote: true do |g| %>
      <div style="display: flex !important;">
        <div class="mx-5"><%= form_field.field.name %></div>
        <div><%= g.input :key_entity, input_html: { value: form_field.key_entity } %></div>    
        <div><%= g.input :settings, input_html: { value: form_field.settings } %></div>  
        <div><%= g.button :submit, class: "btn btn-primary" %>
      </div> 
     
    <% end %>
    <%= button_to "Destroy this form field", form_field, method: :delete %>
     </div>  
  <% end %>

  <%= simple_form_for @form_field do |form| %>

            <div>
              <%= form.input :key_entity %>
            </div>

            <div>
              <%= form.input :settings %>
            </div>

            <div>
              <%= form.select :field_id, options_for_select(Field.all.collect { | field | [field.name, field.id] }, @form.id) %>
            </div>

            <div>
              <%= form.input :form_id, as: :hidden, input_html: {value: @form.id } %>
            </div>
            
            <div>
              <%= form.submit %>
            </div>
      <% end %>
    </div>
  </div>
</div>
  <div>
    <%= link_to "Edit this form", edit_form_path(@form) %> |
    <%= link_to "Back to forms", forms_path %>

    <%= button_to "Destroy this form", @form, method: :delete %>
  </div>
</div>