config/routes.rb
Rails.application.routes.draw do
  resources :form_contract_values
  resources :form_fields
  resources :fields
  resources :forms
  resources :contracts do
    patch :values_form, on: :member
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/field.rb
class Field < ApplicationRecord
    has_many :form_fields, dependent: :destroy
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  before_action :set_field, only: %i[ show edit update destroy ]

  # GET /fields or /fields.json
  def index
    @fields = Field.all
  end

  # GET /fields/1 or /fields/1.json
  def show
  end

  # GET /fields/new
  def new
    @field = Field.new
  end

  # GET /fields/1/edit
  def edit
  end

  # POST /fields or /fields.json
  def create
    @field = Field.new(field_params)

    respond_to do |format|
      if @field.save
        format.html { redirect_to field_url(@field), notice: "Field was successfully created." }
        format.json { render :show, status: :created, location: @field }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fields/1 or /fields/1.json
  def update
    respond_to do |format|
      if @field.update(field_params)
        format.html { redirect_to field_url(@field), notice: "Field was successfully updated." }
        format.json { render :show, status: :ok, location: @field }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fields/1 or /fields/1.json
  def destroy
    @field.destroy

    respond_to do |format|
      format.html { redirect_to fields_url, notice: "Field was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_field
      @field = Field.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def field_params
      params.require(:field).permit(:name, :field_type)
    end
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/views/fields/_field.html.erb
<div id="<%= dom_id field %>">
  <p>
    <strong>Name:</strong>
    <%= field.name %>
  </p>

  <p>
    <strong>Field type:</strong>
    <%= field.field_type %>
  </p>

</div>

app/views/fields/_form.html.erb
<%= form_with(model: field) do |form| %>
  <% if field.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(field.errors.count, "error") %> prohibited this field from being saved:</h2>

      <ul>
        <% field.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :field_type, style: "display: block" %>
    <%= form.text_field :field_type %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/fields/edit.html.erb
<h1>Editing field</h1>

<%= render "form", field: @field %>

<br>

<div>
  <%= link_to "Show this field", @field %> |
  <%= link_to "Back to fields", fields_path %>
</div>

app/views/fields/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Fields</h1>

<div id="fields">
  <% @fields.each do |field| %>
    <%= render field %>
    <p>
      <%= link_to "Show this field", field %>
    </p>
  <% end %>
</div>

<%= link_to "New field", new_field_path %>

app/views/fields/new.html.erb
<h1>New field</h1>

<%= render "form", field: @field %>

<br>

<div>
  <%= link_to "Back to fields", fields_path %>
</div>

app/views/fields/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @field %>

<div>
  <%= link_to "Edit this field", edit_field_path(@field) %> |
  <%= link_to "Back to fields", fields_path %>

  <%= button_to "Destroy this field", @field, method: :delete %>
</div>